import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/header'
import Script from 'next/script'
import { GA_TRACKING_ID } from '@/lib/gtag'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            {/* <head>
        <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
            strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
            {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', ${GA_TRACKING_ID}, {
                page_path: window.location.pathname,
            });
            `}
                </Script>
                </head> */}
        <body className={'max-w-[1200px] m-auto bg-[#111B2AFF]'}>
        <Header/>
        {children}
        </body>
        </html>
    )
}

