import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/header'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
        <body className={'max-w-[1200px] m-auto bg-[#111B2AFF]'}>
        <Header/>
        {children}
        </body>
        </html>
    )
}
